# Generated by Django 5.1 on 2024-08-15 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VOCAL', '보컬'), ('GUITAR', '기타'), ('BASS', '베이스'), ('SYNTH', '신디'), ('DRUM', '드럼')], max_length=6)),
                ('세션장', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_private', models.BooleanField()),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customuser')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.performance')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('cover_name', models.CharField(max_length=255)),
                ('cover_artist', models.CharField(max_length=255)),
                ('original_url', models.URLField()),
                ('cover_url', models.URLField()),
                ('satisfied_sessions', models.ManyToManyField(related_name='songs_satisfying', to='core.session')),
                ('unsatisfied_sessions', models.ManyToManyField(related_name='songs_unsatisfying', to='core.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
    ]
