# Generated by Django 5.1 on 2024-09-09 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="performance",
            old_name="created_datetime",
            new_name="createdDatetime",
        ),
        migrations.RenameField(
            model_name="performance",
            old_name="end_datetime",
            new_name="endDatetime",
        ),
        migrations.RenameField(
            model_name="performance",
            old_name="start_datetime",
            new_name="startDatetime",
        ),
        migrations.RenameField(
            model_name="performance",
            old_name="updated_datetime",
            new_name="updatedDatetime",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="is_private",
            new_name="isFreshmenFixed",
        ),
        migrations.RemoveField(
            model_name="song",
            name="satisfied_sessions",
        ),
        migrations.RemoveField(
            model_name="song",
            name="unsatisfied_sessions",
        ),
        migrations.AddField(
            model_name="performance",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="performance",
            name="representativeImage",
            field=models.ImageField(default="", upload_to="performance/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="icon",
            field=models.ImageField(default="", upload_to="session/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="posterImage",
            field=models.ImageField(blank=True, upload_to="team_poster/"),
        ),
        migrations.AddField(
            model_name="team",
            name="youtubeVideoId",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="MemberSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requiredMemberCount", models.IntegerField()),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="registered_sessions", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.session"
                    ),
                ),
            ],
        ),
    ]
