# Generated by Django 5.1 on 2024-11-12 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ["-createdDatetime"],
                "verbose_name": "피드백",
                "verbose_name_plural": "피드백",
            },
        ),
        migrations.AlterModelOptions(
            name="feedbackanswer",
            options={
                "ordering": ["-createdDatetime"],
                "verbose_name": "피드백 답변",
                "verbose_name_plural": "피드백 답변",
            },
        ),
        migrations.AlterModelOptions(
            name="feedbackquestion",
            options={
                "ordering": ["-createdDatetime"],
                "verbose_name": "피드백 질문",
                "verbose_name_plural": "피드백 질문",
            },
        ),
        migrations.RenameField(
            model_name="feedbackquestion",
            old_name="questionType",
            new_name="answerType",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="description",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="title",
        ),
        migrations.AddField(
            model_name="feedbackquestion",
            name="createdDatetime",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedbackquestion",
            name="updatedDatetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
