# Generated by Django 5.1 on 2024-09-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_created_datetime_performance_createddatetime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="created_datetime",
            new_name="createdDatetime",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="updated_datetime",
            new_name="updatedDatetime",
        ),
        migrations.AlterField(
            model_name="performance",
            name="representativeImage",
            field=models.ImageField(null=True, upload_to="performance/"),
        ),
        migrations.AlterField(
            model_name="session",
            name="icon",
            field=models.ImageField(null=True, upload_to="session/"),
        ),
    ]
