# Generated by Django 5.1 on 2024-11-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_feedback_performance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generation",
            options={
                "ordering": ["order"],
                "verbose_name": "기수",
                "verbose_name_plural": "기수",
            },
        ),
        migrations.AlterModelOptions(
            name="membersession",
            options={
                "ordering": ["team", "session"],
                "verbose_name": "팀 세션",
                "verbose_name_plural": "팀 세션",
            },
        ),
        migrations.AlterModelOptions(
            name="membersessionmembership",
            options={
                "ordering": ["memberSession", "index"],
                "verbose_name": "팀 세션별 멤버",
                "verbose_name_plural": "팀 세션별 멤버",
            },
        ),
        migrations.AlterModelOptions(
            name="performance",
            options={
                "ordering": ["-createdDatetime"],
                "verbose_name": "공연",
                "verbose_name_plural": "공연",
            },
        ),
        migrations.AlterModelOptions(
            name="session",
            options={
                "ordering": ["name"],
                "verbose_name": "세션",
                "verbose_name_plural": "세션",
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["-createdDatetime"],
                "verbose_name": "팀",
                "verbose_name_plural": "팀",
            },
        ),
    ]
