# Generated by Django 5.1 on 2024-11-12 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_generation_options_alter_membersession_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackanswer",
            name="user",
        ),
        migrations.AddField(
            model_name="feedbackanswer",
            name="respondent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="답변자",
            ),
            preserve_default=False,
        ),
    ]
