# Generated by Django 5.1 on 2024-09-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_cover_artist_song_coverartist_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="youtubeVideoId",
            new_name="songYoutubeVideoId",
        ),
        migrations.AddField(
            model_name="team",
            name="songArtist",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="team",
            name="songName",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name="Song",
        ),
    ]
