# Generated by Django 5.1 on 2024-09-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_youtubevideoid_team_songyoutubevideoid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
