# Generated by Django 5.1 on 2024-11-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_feedbackanswer_user_feedbackanswer_respondent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["performance", "-createdDatetime"],
                "verbose_name": "팀",
                "verbose_name_plural": "팀",
            },
        ),
        migrations.AlterField(
            model_name="performance",
            name="createdDatetime",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
        ),
        migrations.AlterField(
            model_name="performance",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="설명"),
        ),
        migrations.AlterField(
            model_name="performance",
            name="endDatetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="종료 일시"),
        ),
        migrations.AlterField(
            model_name="performance",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="장소"
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="name",
            field=models.CharField(max_length=255, verbose_name="이름"),
        ),
        migrations.AlterField(
            model_name="performance",
            name="representativeImage",
            field=models.ImageField(
                null=True, upload_to="performance/", verbose_name="대표 이미지"
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="startDatetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="시작 일시"),
        ),
        migrations.AlterField(
            model_name="performance",
            name="updatedDatetime",
            field=models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
        ),
    ]
