# Generated by Django 5.1 on 2024-11-12 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_team_options_alter_performance_createddatetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="performance",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="core.performance",
                verbose_name="공연 피드백",
            ),
        ),
    ]
