# Generated by Django 5.1 on 2024-09-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_membersession_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersession",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberSessions",
                to="core.team",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="membersession",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.session",
            ),
        ),
    ]
