# Generated by Django 5.1 on 2024-11-13 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_feedback_performance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="membersession",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.session",
                verbose_name="세션",
            ),
        ),
        migrations.AlterField(
            model_name="membersession",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberSessions",
                to="core.team",
                verbose_name="팀",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="createdDatetime",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
        ),
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True, verbose_name="설명"),
        ),
        migrations.AlterField(
            model_name="team",
            name="isFreshmenFixed",
            field=models.BooleanField(default=False, verbose_name="신입 고정 여부"),
        ),
        migrations.AlterField(
            model_name="team",
            name="isSelfMade",
            field=models.BooleanField(default=False, verbose_name="자작곡 여부"),
        ),
        migrations.AlterField(
            model_name="team",
            name="leader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="팀장",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="이름"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="performance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.performance",
                verbose_name="공연",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="posterImage",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team_poster/",
                verbose_name="포스터 이미지",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="songArtist",
            field=models.CharField(blank=True, max_length=50, verbose_name="아티스트"),
        ),
        migrations.AlterField(
            model_name="team",
            name="songName",
            field=models.CharField(blank=True, max_length=50, verbose_name="곡 명"),
        ),
        migrations.AlterField(
            model_name="team",
            name="songYoutubeVideoId",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="유튜브 비디오 ID"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="updatedDatetime",
            field=models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
        ),
    ]
