# Generated by Django 5.1 on 2024-11-13 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_membersession_session_alter_membersession_team_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="generation",
            name="leader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leading_generations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="기장",
            ),
        ),
        migrations.AlterField(
            model_name="generation",
            name="order",
            field=models.DecimalField(
                decimal_places=1, max_digits=3, unique=True, verbose_name="기수"
            ),
        ),
        migrations.AlterField(
            model_name="membersessionmembership",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="멤버",
            ),
        ),
        migrations.AlterField(
            model_name="membersessionmembership",
            name="memberSession",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="core.membersession",
                verbose_name="팀 구성 세션",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="icon",
            field=models.ImageField(
                null=True, upload_to="session/", verbose_name="아이콘"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="name",
            field=models.CharField(
                choices=[
                    ("보컬", "보컬"),
                    ("기타", "기타"),
                    ("베이스", "베이스"),
                    ("신디", "신디"),
                    ("드럼", "드럼"),
                    ("현악기", "현악기"),
                    ("관악기", "관악기"),
                ],
                max_length=6,
                unique=True,
                verbose_name="이름",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="세션장",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leading_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="세션장",
            ),
        ),
    ]
