# Generated by Django 5.1 on 2024-09-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_session_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="endDatetime",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="performance",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="performance",
            name="startDatetime",
            field=models.DateTimeField(blank=True),
        ),
    ]
