# Generated by Django 5.1.5 on 2025-03-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_generation_leader_alter_generation_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='songYoutubeVideoId',
            new_name='songYoutubeVideoUrl',
        ),
    ]
