# Generated by Django 5.1 on 2024-09-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_performance_enddatetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="endDatetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="performance",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="performance",
            name="startDatetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
