# Generated by Django 5.1 on 2024-09-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_performance_enddatetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
