# Generated by Django 5.1 on 2024-10-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_performance_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membersession",
            name="requiredMemberCount",
        ),
    ]
