# Generated by Django 5.1 on 2024-10-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_membersession_requiredmembercount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membersession",
            name="members",
        ),
    ]
