# Generated by Django 5.1 on 2024-10-04 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_membersession_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberSessionMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.membersession",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="membersession",
            name="members",
            field=models.ManyToManyField(
                related_name="registered_sessions",
                through="core.MemberSessionMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
