# Generated by Django 5.1 on 2024-10-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_generation_order"),
        ("core", "0017_membersessionmembership_membersession_members"),
    ]

    operations = []
