# Generated by Django 5.1 on 2024-10-04 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_membersessionmembership_unique_member_session_custom_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membersessionmembership",
            name="unique_member_session_custom_user",
        ),
        migrations.RenameField(
            model_name="membersessionmembership",
            old_name="custom_user",
            new_name="member",
        ),
        migrations.RemoveField(
            model_name="membersession",
            name="members",
        ),
        migrations.RemoveField(
            model_name="membersessionmembership",
            name="member_session",
        ),
        migrations.AddField(
            model_name="membersessionmembership",
            name="index",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="membersessionmembership",
            name="memberSession",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="core.membersession",
            ),
            preserve_default=False,
        ),
    ]
