# Generated by Django 5.1 on 2024-10-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_membersessionmembership_member"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="membersession",
            constraint=models.UniqueConstraint(
                fields=("team", "session"), name="unique_team_session"
            ),
        ),
    ]
