# Generated by Django 5.1 on 2024-11-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_membersession_unique_team_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='isSelfMade',
            field=models.BooleanField(default=False),
        ),
    ]
