# Generated by Django 5.1 on 2024-11-04 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_team_isselfmade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="performance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.performance"
            ),
        ),
    ]
