# Generated by Django 5.1 on 2024-11-09 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_team_performance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                (
                    "questionType",
                    models.CharField(
                        choices=[("string", "String"), ("int", "Integer")],
                        default="string",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField()),
                ("isRequired", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("createdDatetime", models.DateTimeField(auto_now_add=True)),
                ("updatedDatetime", models.DateTimeField(auto_now=True)),
                ("startDatetime", models.DateTimeField()),
                ("endDatetime", models.DateTimeField()),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="core.performance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField()),
                ("createdDatetime", models.DateTimeField(auto_now_add=True)),
                ("updatedDatetime", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.feedbackquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="core.feedback",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feedbackquestion",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="core.feedbacktemplate",
            ),
        ),
    ]
