# Generated by Django 5.1 on 2024-08-16 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=40)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(upload_to='')),
                ('position', models.CharField(choices=[('PRESIDENT', '회장'), ('VICE_PRESIDENT', '부회장'), ('GENERAL_AFFAIRS', '총무'), ('MEMBER', '일반')], max_length=30)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.generation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_departments', to='user.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.department'),
        ),
    ]
