# Generated by Django 5.1 on 2024-11-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["generation__order", "name"],
                "verbose_name": "유저",
                "verbose_name_plural": "유저",
            },
        ),
    ]
