# Generated by Django 5.1 on 2024-09-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_created_datetime_performance_createddatetime_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="created_datetime",
            new_name="createdDatetime",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="profile_image",
            new_name="profileImage",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="updated_datetime",
            new_name="updatedDatetime",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="session",
        ),
        migrations.AddField(
            model_name="customuser",
            name="sessions",
            field=models.ManyToManyField(related_name="users", to="core.session"),
        ),
    ]
