# Generated by Django 5.1 on 2024-09-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_created_datetime_customuser_createddatetime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="profileImage",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(max_length=20),
        ),
    ]
