# Generated by Django 5.1 on 2024-09-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_profileimage_customuser_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
