# Generated by Django 5.1 on 2024-11-19 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_generation_leader_alter_generation_order_and_more"),
        ("user", "0003_alter_customuser_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="generation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.generation",
                verbose_name="기수",
            ),
        ),
    ]
